export const STRINGS = {
  fr: {
    title: '🧮 Token<span class="fr-word">ette</span>',
    lede: "Une IA ne lit pas des mots, mais des morceaux de texte, appelés <em>jetons</em>. Chaque jeton se paie — en argent, et en place dans sa mémoire. Écris la même phrase en anglais et en français, et compte.",
    templatesLabel: "Essaie un exemple, ou écris le tien plus bas",
    run: "Lancer →",
    english: "Anglais", french: "Français", tokens: "jetons",
    fromFrench: "Traduire depuis le français", fromEnglish: "Traduire depuis l’anglais",
    translating: "Traduction…",
    cutWith: "Découpé par", recent: "Récent", older: "Plus ancien",
    chars: (n) => `${n} caractères`,
    loading: "Chargement du compteur (environ 3 Mo, une seule fois)…",
    loadFailed: "Le compteur n’a pas pu se charger. Vérifie ta connexion, puis recharge la page.",
    empty: "Écris quelque chose au-dessus.",
    more: (n) => ` … et ${n} jetons de plus`,
    multi: "plusieurs jetons pour un seul caractère",
    waiting: "Écris dans les deux cases pour comparer.",
    more_: (p) => `En français, ce texte coûte <b>${p}</b> de jetons en plus.`,
    less_: (p) => `En français, ce texte coûte <b>${p}</b> de jetons en moins.`,
    same_: "Les deux langues coûtent autant de jetons ici.",
    scale: (en, fr) => `Pour ${en} jetons en anglais, compte environ ${fr} en français.`,
    barTitleRecent: "Récent · GPT-4o, GPT-5",
    barTitleOlder: "Plus ancien · GPT-4, Llama 3",
    measuredTitle: "Sur de vrais textes longs",
    measuredLede: "Les 6 skills CADRER entiers — environ 18\u00a0000 caractères d’instructions — passés dans 8 tokenizers publics. Le point montre combien de jetons le français coûte pour 1 jeton en anglais.",
    plotCaption: "Anglais ≈ 4 200 jetons partout. Version française : une traduction de travail, au tutoiement. La zone rosée couvre les tokenizers actuels.",
    n1t: "Le cas de Claude",
    n1: "Le découpeur de Claude n’est pas public. Anthropic offre un compteur exact, mais il demande une clé d’API. Ici, on mesure avec les découpeurs publics, et dans tous ceux testés, l’anglais coûte moins cher.",
    n2t: "Pourquoi le français coûte plus",
    n2: "Deux raisons. La phrase est plus longue — articles, prépositions, terminaisons. Les découpeurs, eux, ont surtout appris sur de l’anglais : un mot anglais courant tient souvent en un jeton, un mot français se coupe plus souvent, surtout autour des accents.",
    n3t: "Ce qui reste sur ton ordinateur",
    n3: "Le comptage se fait dans ton navigateur, et ce que tu écris n’est envoyé nulle part. Seul le bouton « Traduire », quand il est là, envoie le texte à Claude avec ton accord.",
    translateErrors: {
      not_granted: "Traduction refusée. Tu peux écrire la version toi-même.",
      rate_limited: "Trop de traductions d’un coup. Réessaie dans une minute.",
      default: "La traduction n’a pas marché. Écris la version toi-même, ou réessaie plus tard.",
    },
    translateNote: "Traduit par Claude — corrige-le si tu le dirais autrement.",
    uiGroup: "Langue de la page",
  },
  en: {
    title: '🧮 Token<span class="fr-word">ette</span>',
    lede: "An AI doesn’t read words: it reads chunks of text called <em>tokens</em>. Every token costs — in money, and in room in its memory. Write the same sentence in English and in French, and count.",
    templatesLabel: "Try an example, or write your own below",
    run: "Run →",
    english: "English", french: "French", tokens: "tokens",
    fromFrench: "Translate from French", fromEnglish: "Translate from English",
    translating: "Translating…",
    cutWith: "Cut by", recent: "Recent", older: "Older",
    chars: (n) => `${n} characters`,
    loading: "Loading the counter (about 3 MB, once)…",
    loadFailed: "The counter couldn’t load. Check your connection, then reload the page.",
    empty: "Write something above.",
    more: (n) => ` … and ${n} more tokens`,
    multi: "several tokens for a single character",
    waiting: "Write in both boxes to compare.",
    more_: (p) => `In French, this text costs <b>${p}</b> more tokens.`,
    less_: (p) => `In French, this text costs <b>${p}</b> fewer tokens.`,
    same_: "Both languages cost the same number of tokens here.",
    scale: (en, fr) => `For every ${en} tokens in English, expect about ${fr} in French.`,
    barTitleRecent: "Recent · GPT-4o, GPT-5",
    barTitleOlder: "Older · GPT-4, Llama 3",
    measuredTitle: "And on real, long texts?",
    measuredLede: "All 6 CADRER skills — about 18,000 characters of instructions — run through 8 public tokenizers. Each dot shows how many French tokens you pay for 1 English token.",
    plotCaption: "English ≈ 4,200 tokens everywhere. French version: a working translation, in the informal “tu”. The pink band covers today’s tokenizers.",
    n1t: "What about Claude?",
    n1: "Claude’s tokenizer isn’t public. Anthropic offers an exact counter, but it needs an API key. So this page measures with the public ones: in every one tested, English costs less.",
    n2t: "Why French costs more",
    n2: "Two reasons. The sentence is longer — articles, prepositions, endings. And tokenizers learned mostly from English: a common English word often fits in one token, while a French word gets cut more often, especially around accents.",
    n3t: "What stays on your computer",
    n3: "Counting happens in your browser: what you type is sent nowhere. Only the “Translate” button, when it shows, sends the text to Claude, with your permission.",
    translateErrors: {
      not_granted: "Translation declined. You can write the other version yourself.",
      rate_limited: "Too many translations at once. Try again in a minute.",
      default: "The translation didn’t work. Write the other version yourself, or try again later.",
    },
    translateNote: "Translated by Claude — fix it if you’d say it differently.",
    uiGroup: "Page language",
  },
};
